### ISSUE TITLE
Add TravisCI integration

### ISSUE THREAD

**Issue by cyroxx** [sea-watch/SAR-Server#5]
In order to maintain the stability of the code base, we should add the [TravisCI](http://travis-ci.org/) integration.

**Comment by niczem** [comment]
I granted acces for the repo. What are the next steps?

**Comment by x3ro** [comment]
You can go to https://travis-ci.org/ and enable it for this repository. I can add a Travis configuration sometime next week.

**Comment by niczem** [comment]
Matthias already added the repo abd I approved the request. It would ne awesome if you could add the configuration :)

**Comment by x3ro** [comment]
<img width="956" alt="screen shot 2017-01-16 at 20 23 24" src="https://cloud.githubusercontent.com/assets/243719/21996269/ac70be72-dc29-11e6-86ef-2a87006f6ab0.png">

**Comment by x3ro** [comment]
Done.
